# workspace/.github/workflows/toc.yml
name: Auto Cheatsheets TOC

on:
  push:
    branches: [ main ]
    paths:
      - 'cheatsheets/**/*.md'
      - 'README.md'
      - '.github/workflows/toc.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 1) Сгенерировать TOC внутри всех шпаргалок
      - name: Generate TOC in cheatsheets
        run: |
          npx -y doctoc cheatsheets --github --maxlevel 3 --title "## Оглавление"

      # 2) Пересобрать блок в README — ОТКРЫТЫЙ список (без <details> и без заголовка "Оглавление")
      - name: Rebuild cheatsheets section in README
        shell: bash
        run: |
          set -euo pipefail
          README="README.md"
          START="<!-- START:cheatsheets-toc -->"
          END="<!-- END:cheatsheets-toc -->"

          {
            echo "$START"
            echo
            # Обходим все md в cheatsheets
            while IFS= read -r FILE; do
              REL="$FILE"

              # Заголовок берем из первого H1 в файле, иначе — из имени файла
              TITLE="$(awk 'match($0,/^# +(.+)/,m){print m[1]; exit}' "$FILE")"
              if [[ -z "$TITLE" ]]; then
                BASE="$(basename "$FILE" .md)"
                TITLE="$(echo "$BASE" | sed 's/-/ /g; s/\b\(.\)/\u\1/g')"
              fi

              # Первая строка — ссылка на файл
              echo "- [$TITLE]($REL)"

              # Вырезаем doctoc-блок, убираем сам заголовок "Оглавление" и комментарии,
              # чиним относительные якоря, делаем список вложенным (два пробела слева)
              awk '/<!-- START doctoc -->/{p=1;next}/<!-- END doctoc -->/{p=0}p' "$FILE" \
                | sed -e '1{/^## \([Oo]главление\|[Tt]able of [Cc]ontents\)/d;}' \
                      -e '/^<!--/d' \
                | sed 's|](#|]('"$REL"'#|g' \
                | sed 's/^/  /'

              echo
            done < <(find cheatsheets -type f -name "*.md" | sort)
            echo "$END"
          } > __TOC__.md

          # Вклеиваем новый блок в README
          awk -v start="$START" -v end="$END" -v file="__TOC__.md" '
            BEGIN{inblk=0}
            $0==start {print; while ((getline l < file)>0) print l; inblk=1; next}
            $0==end   {inblk=0; next}
            !inblk    {print}
          ' "$README" > __README__.md

          mv __README__.md "$README"
          rm -f __TOC__.md

      # 3) Если есть изменения — открываем/обновляем PR
      - name: Detect changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create/Update PR
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/toc-update
          commit-message: "docs(toc): update cheatsheets TOC"
          title: "docs(toc): update cheatsheets TOC"
          body: "Automated update of cheatsheets TOC in README and files."
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          labels: docs, automation
