name: Auto Cheatsheets TOC

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.md'

permissions:
  contents: write

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 1) Генерим TOC внутри всех шпаргалок (ВНИМАНИЕ: путь без префикса workspace/)
      - name: Generate TOC in cheatsheets
        run: |
          npx -y doctoc cheatsheets --github --maxlevel 3 --title "## Оглавление"

      # 2) Вставляем сворачиваемые оглавления в README (корень репозитория)
      - name: Inject cheatsheets TOC into README
        shell: bash
        run: |
          set -e
          README="README.md"
          TOC_START="<!-- START:cheatsheets-toc -->"
          TOC_END="<!-- END:cheatsheets-toc -->"

          # собираем новый блок
          {
            echo "${TOC_START}"
            echo
            find cheatsheets -type f -name "*.md" | sort | while read FILE; do
              REL="$FILE"
              NAME="$(basename "$FILE" .md | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')"

              echo "<details>"
              echo "  <summary><strong><a href=\"$REL\">$NAME</a></strong> — оглавление</summary>"
              echo

              # вытаскиваем doctoc-блок из файла и правим ссылки на якоря
              awk '/<!-- START doctoc -->/{flag=1;next}/<!-- END doctoc -->/{flag=0}flag' "$FILE" \
                | sed "s|](#|]($REL#|g"

              echo
              echo "</details>"
              echo
            done
            echo "${TOC_END}"
          } > README.new

          # заменяем блок в README между маркерами
          awk -v start="${TOC_START}" -v end="${TOC_END}" '
            BEGIN{inblk=0}
            {
              if ($0==start){print; while(getline l<"README.new"){print l}; inblk=1; next}
              if ($0==end){inblk=0}
              if (!inblk) print
            }
          ' "${README}" > README.tmp && mv README.tmp "${README}"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(toc): auto update cheatsheets TOC in README [skip ci]"
          file_pattern: "**/*.md"
