# workspace/.github/workflows/toc.yml
name: Auto Cheatsheets TOC

on:
  push:
    branches: [ main ]
    paths:
      - 'cheatsheets/**/*.md'
      - 'README.md'
      - '.github/workflows/toc.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure doctoc placeholders exist after first H1
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t FILES < <(find cheatsheets -type f -name '*.md' | sort)
          for FILE in "${FILES[@]}"; do
            if ! grep -q "<!-- START doctoc" "$FILE"; then
              awk '
                BEGIN{placed=0}
                placed==0 && /^# / {
                  print
                  print ""
                  print "<!-- START doctoc -->"
                  print "<!-- END doctoc -->"
                  print ""
                  placed=1
                  next
                }
                { print }
              ' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
            fi
          done

      - name: Generate TOC inside cheatsheets
        run: npx -y doctoc cheatsheets --github --maxlevel 3 --title "## Оглавление"

      # >>> Единственное существенное отличие — формируем ОТКРЫТЫЙ список без <details> и без строки "Оглавление"
      - name: Inject cheatsheets TOC into README (open list, no heading)
        shell: bash
        run: |
          set -euo pipefail

          README="README.md"
          TOC_START="<!-- START:cheatsheets-toc -->"
          TOC_END="<!-- END:cheatsheets-toc -->"

          TMP="README.new"
          : > "$TMP"
          echo "$TOC_START" >> "$TMP"
          echo >> "$TMP"

          # Собираем список шпаргалок
          mapfile -t FILES < <(find cheatsheets -type f -name '*.md' | sort)
          for FILE in "${FILES[@]}"; do
            REL="$FILE"
            # Заголовок берём из первого H1
            TITLE="$(grep -m1 -E '^# ' "$FILE" | sed 's/^# \+//; s/\r$//')"
            if [[ -z "$TITLE" ]]; then
              BASE="$(basename "$FILE" .md)"
              TITLE="$(echo "$BASE" | sed 's/-/ /g; s/\b\(.\)/\u\1/g')"
            fi

            # Извлечь doctoc-блок, убрать строку "## Оглавление" и комментарии, починить якоря,
            # сделать это вложенным списком (два пробела слева)
            TOC_CONTENT="$(awk '/<!-- START doctoc -->/{f=1;next} /<!-- END doctoc -->/{f=0} f' "$FILE" \
              | sed -E '1{/^##[[:space:]]+(Оглавление|Table of Contents)$/Id;}' \
              | sed -E '/^<!--/d' \
              | sed "s|](#|]($REL#|g" \
            )"

            # Верхний пункт — ссылка на файл
            echo "- [$TITLE]($REL)" >> "$TMP"
            # Вложенный список (если есть)
            if [[ -n "$TOC_CONTENT" ]]; then
              printf '%s\n' "$TOC_CONTENT" | sed 's/^/  /' >> "$TMP"
              echo >> "$TMP"
            fi
          done

          echo "$TOC_END" >> "$TMP"

          # Заменить блок в README на собранный
          awk -v start="$TOC_START" -v end="$TOC_END" '
            BEGIN {inblk=0}
            {
              if ($0==start) { print; while ((getline l < "README.new") > 0) print l; inblk=1; next }
              if ($0==end)   { inblk=0; next }
              if (!inblk) print
            }
          ' "$README" > "$README.tmp" && mv "$README.tmp" "$README"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(toc): auto update cheatsheets TOC"
          file_pattern: |
            cheatsheets/**/*.md
            README.md
